/**
 * 遊戲設定常數
 * 依賴：無
 */
const RPG = {
  SAVE_KEY_PREFIX: 'myrpg_save_',
  MAP_SIZE: 10,
  ENCOUNTER_CHANCE: 0.38,
  ENCOUNTER_CHANCE_EARLY: 0.20,
  ENCOUNTER_CHANCE_MID: 0.28,
  ESCAPE_CHANCE: 0.35,
  DEFEND_DAMAGE_REDUCE: 0.4,
};
